### PR TITLE
Hw3hw5

### PR DESCRIPTION
**Pull request by JessicaMadeira97**
Tried again

### CODE REVIEW

**Comment by floridop** [comment]
uh, it was better if you left the file where it was before... it will help me automate correction.
Please move it to 
`jessicamad/tutorial3/homework3/musicstats.sh`

**Comment by JessicaMadeira97** [comment]
Sorry, I didn’t notice it. Think I fixed it already.


Enviado do meu iPhone

No dia 01/10/2019, às 15:14, Florido Paganelli <notifications@github.com> escreveu:

**Comment by JessicaMadeira97** [comment]
Trying the pull request again

**Comment by floridop** [comment]
Hi 
I think it didn't work, the file is still deleted. I think I can explain what happened. Wherever you're applying these changes they appear before mine, if you're doing it from the virtual machine make sure the date is correct.
you can fix the date with the command
```sudo date -s '2019-11-20 15:26' ```

**Comment by floridop** [comment]
Sorry forget my comment. The file is correct. You do not need to do anything. Thanks!

**Pull request merged**
